// src/types/index.ts

export type FileType = 'pdf' | 'image';

export interface UploadedFile {
	id: string;
	file: File;
	type: FileType;
	name: string;
	size: number;
	preview?: string; // base64 or object URL for images
}

export type PageStatus = 'pending' | 'processing' | 'done' | 'error';

export interface PageResult {
	pageNumber: number;
	imageBase64: string; // the rendered page image sent to the OCR model
	arabicText: string; // extracted Arabic OCR text
	status: PageStatus;
	error?: string;
	tokenCount?: number; // tokens generated by the model
	maxTokens?: number; // model's max token limit
	duration?: number; // seconds taken by the Python API
}

export interface DigitizationJob {
	id: string;
	file: UploadedFile;
	sourceFiles?: File[]; // populated for multi-image batches
	totalPages: number;
	currentPage: number;
	pages: PageResult[];
	status: 'idle' | 'processing' | 'complete' | 'error';
	startedAt?: Date;
	completedAt?: Date;
}
